### PR TITLE
printer tree BUGFIX implicit case in compiled tree

### LINKED ISSUE #1574: ly2 yanglint -f tree frr-filter.yang crash
ly2 yanglint -f tree crashes on https://github.com/FRRouting/frr/blob/master/yang/frr-filter.yang:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b62dc5 in trop_leaflist_refpath (pn=0x55555578c360) at /home/iryzhov/libyang/src/printer_tree.c:2567
2567	    return list->type.path ? list->type.path->expr : NULL;
(gdb) bt
#0  0x00007ffff7b62dc5 in trop_leaflist_refpath (pn=0x55555578c360) at /home/iryzhov/libyang/src/printer_tree.c:2567
#1  0x00007ffff7b62e72 in trop_node_charptr (flags=8, f=0x7ffff7b62d9a <trop_leaflist_refpath>, pn=0x55555578c360)
    at /home/iryzhov/libyang/src/printer_tree.c:2623
#2  0x00007ffff7b6316e in trop_resolve_type (pn=0x55555578c360) at /home/iryzhov/libyang/src/printer_tree.c:2730
#3  0x00007ffff7b64010 in troc_read_node (ca=..., tc=0x7fffffffe2b0) at /home/iryzhov/libyang/src/printer_tree.c:3143
#4  0x00007ffff7b642da in troc_modi_next_child (ca=..., tc=0x7fffffffe2b0) at /home/iryzhov/libyang/src/printer_tree.c:3207
#5  0x00007ffff7b64ba8 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3466
#6  0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#7  0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#8  0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#9  0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#10 0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#11 0x00007ffff7b64c00 in trb_print_nodes (wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3471
#12 0x00007ffff7b650a1 in trb_print_subtree_nodes (max_gap_before_type=7, wr=..., ca=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3620
#13 0x00007ffff7b65321 in trb_print_family_tree (wr=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3688
#14 0x00007ffff7b657e8 in trm_print_section_as_family_tree (ks=..., pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3871
#15 0x00007ffff7b65937 in trm_print_module_section (pc=0x7fffffffe2e0, tc=0x7fffffffe2b0)
    at /home/iryzhov/libyang/src/printer_tree.c:3912
#16 0x00007ffff7b65dd9 in trm_print_sections (pc=0x7fffffffe2e0, tc=0x7fffffffe2b0) at /home/iryzhov/libyang/src/printer_tree.c:4087
#17 0x00007ffff7b6608a in tree_print_module (out=0x555555784580, module=0x555555785640, UNUSED_options=0,
    line_length=18446744073709551615) at /home/iryzhov/libyang/src/printer_tree.c:4122
#18 0x00007ffff7b4e2f7 in lys_print_module (out=0x555555784580, module=0x555555785640, format=LYS_OUT_TREE, line_length=0, options=0)
    at /home/iryzhov/libyang/src/printer_schema.c:71
#19 0x00005555555595bf in main_ni (argc=4, argv=0x7fffffffe588) at /home/iryzhov/libyang/tools/lint/main_ni.c:734
#20 0x0000555555557df0 in main (argc=4, argv=0x7fffffffe588) at /home/iryzhov/libyang/tools/lint/main.c:45
```

### PR DESCRIPTION
**Pull request by lePici**
Fix #1574

### CODE REVIEW

File: src/printer_tree.c [hunk 1]
```diff
@@ -2488,6 +2488,29 @@ tro_read_module_name(const struct trt_tree_ctx *tc)
...
+ */
+static struct trt_node
+tro_create_implicit_case_node(struct trt_node node)
+{
+    struct trt_node ret;
+
+    ret.status = node.status;
+    ret.flags = TRD_FLAGS_TYPE_EMPTY;
+    ret.name.type = TRD_NODE_CASE;
+    /* TODO: ret.name.module_prefix is not supported right now. */
```
Comment (michalvasko) [inline src/printer_tree.c:2504]: Why cannot you just use the prefix/name of the descendant?

File: src/schema_compile_node.c [hunk 2]
```diff
@@ -3311,7 +3312,20 @@ lys_compile_node_choice_child(struct lysc_ctx *ctx, struct lysp_node *child_p, s
 
 free_fake_node:
         /* free the fake parsed node and correct pointers back */
+
         cs_p->child = NULL;
+        if (ctx->ctx->flags & LY_CTX_SET_PRIV_PARSED) {
+            /* compiled node cannot point to the implicit case node */
+            LY_LIST_FOR((struct lysc_node *)((struct lysc_node_choice *)node)->cases, compiled_case) {
```
Comment (michalvasko) [inline src/schema_compile_node.c:3319]: A loop to find the last element is redundant, just take the first child `prev` pointer and you have it.

**Review by michalvasko — CHANGES_REQUESTED** [review]

File: src/printer_tree.c (hunk 1 above)
Comment (lePici) [reply src/printer_tree.c:2504]: It is related to this -> [rfc](https://datatracker.ietf.org/doc/html/rfc8340):
>          If the node is augmented into the tree from another module,
>          its name is printed as <prefix>:<name>, where <prefix> is the
>          prefix defined in the module where the node is defined.

I haven't dealt with this prefix thing yet, because Radek once told me I didn't have to deal with it. I don't know if the situation has changed.
It's not the only place I don't deal with the prefix. This can be found variously in the printer tree code.

File: src/schema_compile_node.c (hunk 2 above)
Comment (lePici) [reply src/schema_compile_node.c:3319]: ok, great

File: src/printer_tree.c (hunk 1 above)
Comment (lePici) [reply src/printer_tree.c:2504]: However, I will add the prefix copy and delete the TODO. I will add the prefix implementation in another future PR.

**Review by michalvasko — APPROVED** [review]
